---
name: Open Pull Request when an `auto-pr` is pushed

on:
  push:
    branches:
      - 'auto-pr/**'

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: "open a pull request"
        id: open-pr
        run: |
          # this runs everytime the PR gets pushed too, whilst you can only create a PR a single time
          # so we should be smarter, but piping this to /dev/null is a fine workaround for MVP
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -B "$PR_TARGET" > /dev/null

        env:
          PR_TITLE: "Auto PR: Regenerating based on (${{ github.sha }})"
          PR_BODY: "Regenerating the Terraform Provider based on the latest changes"
          PR_TARGET: "main"
          GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TERRAFORM_TOKEN }}
