---
name: Breaking Schema Changes

permissions:
  contents: read
  pull-requests: read


on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/breaking-change-detection.yaml'
      - 'vendor/**'
      - 'internal/**.go'

concurrency:
  group: 'breakingChange-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-breaking-change-detection.sh