---
name: Increment Milestone

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  issues: write
  contents: read

jobs:
  increment-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: "Increment Milestone"
        shell: bash
        run: bash ./scripts/increment-milestone.sh -u https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/milestones -r ${{github.ref_name}} -t ${{secrets.GITHUB_TOKEN}}