name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  issue_comment_triage:
    permissions:
      issues: write  # for actions-ecosystem/action-remove-labels to remove issue labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: stale
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: waiting-response
