---
name: Set Milestone
on:
  pull_request:
    branches: [main]
    types: ['closed']
#    paths:
#      - '**.go'
#      - 'vendor/**'
#      - '.github/workflows/**'

jobs:
  set-milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: actions/github-script@v5
      - run: make link-milestone
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

