name: Save Artifacts

on:
  # This file is reused, and called from other workflows
  workflow_call:

jobs:
  save-artifacts:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.repository_owner }} > wr_actions/ghowner.txt
          echo ${{ github.event.repository.name }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: artifact
          path: wr_actions
          retention-days: 1
