---
name: TeamCity Config Test

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/teamcity-test.yaml'
      - '!.teamcity/components/generated/**'
      - '!.teamcity/target/**'
      - '.teamcity/**'

concurrency:
  group: 'tctest-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  teamcity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: zulu
          java-version: 11
          java-package: jdk
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: make teamcity-test
