---
name: Terraform Schema Linting

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/tflint.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'tflint-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  tflint:
    runs-on: [custom, linux, medium]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make tflint
  save-artifacts-on-fail:
    if: ${{ needs.tflint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
