---
name: Unit Tests
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.17.5'
      - run: bash scripts/gogetcookie.sh
      - run: make test
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
