---
name: Validate Examples
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'examples/**'

concurrency:
  group: 'examples-${{ github.head_ref }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.17.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make validate-examples
