---
name: Website Linting

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "website/**"
      - ".github/workflows/**"

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --global markdownlint-cli
      - run: markdownlint './website/docs/**/*.markdown' --disable MD013
        continue-on-error: false
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18.5"
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make website-lint
